
---

- name: Check Linux distribution
  debug: var="ansible_os_family"

- block:   #=========DEBIAN BLOCK============

  - name: Install DEBIAN Packages
    apt: 
     pkg:
      - haproxy
      - php-xml
      - php-mysqli
      - python3-mysqldb
      - python-pymysql
      - python3-pymysql
      - python3
      - python3-pip
      - iptables-persistent
     state: latest
     update_cache: yes
     cache_valid_time: 86400

  - name: Start Services on Debian
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items:
       - haproxy
       - netfilter-persistent

  - name: Check Server Status
    service: 
     name: "{{ item }}"
    with_items:
       - haproxy
       - netfilter-persistent

  - name: Reconfig symbolic link to python
    ansible.builtin.file:
     src: /usr/bin/python3
     dest: /usr/bin/python
     state: link

  - name: Download Config HAProxy
    copy:
     src: Debian/haproxy.cfg
     dest: /etc/haproxy

  - name: Download Config IPtables
    copy:
     src: Debian/rules.v4
     dest: /etc/iptables

  - name: Restart HAProxy
    service: name=haproxy state=restarted

  - name: Restart IPtables
    service: name=netfilter-persistent state=restarted


  when: ansible_os_family == "Debian"
